name: SmartBear Supported Issue Label Added

on:
  issues:
    types:
      - labeled

jobs:
  call-workflow:
    uses: pactflow/.github/.github/workflows/smartbear-issue-label-added.yml@311810042cf15c50533a163e6e2e9982f41866ad # main
    secrets: inherit
